
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab08_2(

	input 		          		CLOCK_50,
	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [9:0]counter;
parameter a = 1;
wire [7:0]data;
wire ready,overflow,together,off,if_shift,if_caps;
wire [7:0] PS;
wire [3:0]state;

//=======================================================
//  Structural coding
//=======================================================
ps2_keyboard PS_(CLOCK_50,a,PS2_CLK,PS2_DAT,data,ready,overflow);
higher HIGH(CLOCK_50,ready,data,PS,counter,together,if_caps,if_shift,off,state);
trans TRANS(CLOCK_50,off,PS,if_caps,if_shift,counter,HEX5,HEX4,HEX0,HEX1,HEX2,HEX3);

assign LEDR[0] = together;
/*assign LEDR[1] = off;
assign LEDR[2] = state[0];
assign LEDR[3] = state[1];
assign LEDR[4] = state[2];*/
endmodule
