
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab08_1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire [9:0]counter;
parameter a = 1;
wire [7:0]data;
wire ready,overflow,off;
wire [7:0] PS;

//=======================================================
//  Structural coding
//=======================================================
ps2_keyboard PS_(CLOCK_50,a,PS2_CLK,PS2_DAT,data,ready,overflow);
higher HIGH(CLOCK_50,ready,data,PS,counter,off);
trans TRANS(CLOCK_50,off,PS,counter,HEX5,HEX4,HEX0,HEX1,HEX2,HEX3);

assign LEDR[2] = off;

endmodule
