
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab07(

	//////////// KEY //////////
	input 		     [3:0]		KEY,//KEY0作为写使能，KEY1作为clk，KEY23作为RAM2的写入数据

	//////////// SW //////////
	input 		     [9:0]		SW,//SW0-3是读地址，4-7是写地址，8-9是写入数据
	output				  [9:0]     LED,

	//////////// Seg7 //////////
	output	     [6:0]		HEX0,
	output        [6:0]		HEX1,
	output 	     [6:0]		HEX2,
	output 	     [6:0]		HEX3,
	output 	     [6:0]		HEX4,
	output 	     [6:0]		HEX5,
	output [7:0] dout
);
RAM1 ram1(dout,KEY[1], KEY[0], SW[7:4], SW[3:0], SW[9:8],HEX0,HEX1);
RAM2 ram2(KEY[1], KEY[3:2], SW[3:0], SW[7:4], KEY[0], LED[7:0]);


endmodule
