
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab09_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [23:0] vga_data;
wire [9:0] h_addr; //提供给上层模块的当前扫描像素点坐标 
wire [9:0] v_addr; 
wire [11:0] q;
assign VGA_SYNC_N = 1'b0;
wire [9:0]pv_addr;
wire [9:0]ph_addr;
//=======================================================
//  Structural coding
//=======================================================
clkgen #(25000000) my_vgaclk(CLOCK_50,SW[0],1'b1,VGA_CLK);
vga_ctrl my_vga(VGA_CLK,SW[0],vga_data,h_addr,v_addr,VGA_HS,VGA_VS,VGA_BLANK_N,VGA_R,VGA_G,VGA_B);
mydesign whl(CLOCK_50,vga_data,h_addr,v_addr,q,pv_addr,ph_addr);
ram_ myram(CLOCK_50,0,(v_addr-pv_addr)*100+(h_addr-ph_addr),0,0,q);
endmodule
