
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab10_1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	
	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire clk_i2c;
wire reset;
wire [15:0] audiodata;
wire [7:0]data;
wire ready,overflow,if_shift,off;
wire [7:0] PS;
wire [15:0] sound;

//=======================================================
//  Structural coding
//=======================================================
assign reset = ~SW[0];
assign LEDR[7] = off;
audio_clk u1(CLOCK_50, reset,AUD_XCK, LEDR[9]);
//assign LEDR[6:3] = left;

//I2C part
clkgen #(10000) my_i2c_clk(CLOCK_50,reset,1'b1,clk_i2c);  //10k I2C clock  
I2C_Audio_Config myconfig(clk_i2c, SW[0],SW[3:1],FPGA_I2C_SCLK,FPGA_I2C_SDAT,LEDR[2:0]);
I2S_Audio myaudio(AUD_XCK,SW[0],AUD_BCLK, AUD_DACDAT, AUD_DACLRCK, audiodata);
Sin_Generator sin_wave(AUD_DACLRCK, SW[0], sound, audiodata);//
ps2_keyboard PS_(CLOCK_50,1'b1,PS2_CLK,PS2_DAT,data,ready,overflow);
higher HIGH(CLOCK_50,ready,data,PS,if_shift,off);
mydesign whl(CLOCK_50,PS,if_shift,sound,off);

endmodule

